#!/usr/bin/python3

import maker
import os

print('''\n \ \        / /          | | (_)   | |   |  \/  |     | |            
  \ \  /\  / /__  _ __ __| | |_ ___| |_  | \  / | __ _| | _____ _ __ 
   \ \/  \/ / _ \| '__/ _` | | / __| __| | |\/| |/ _` | |/ / _ \ '__|
    \  /\  / (_) | | | (_| | | \__ \ |_  | |  | | (_| |   <  __/ |   
     \/  \/ \___/|_|  \__,_|_|_|___/\__| |_|  |_|\__,_|_|\_\___|_|   ''')
print("\nType \"help\" to see all available commands\n")

availablemodes = '''Password
Number'''

help = '''Available Commands:
mode (yes, only one command right now 😔)'''

while True:
	userinput = input('> ')
	
	if userinput.lower().startswith('mode'):
		try:
			if userinput.split()[1] == 'password':
				print('\nMode set to password list\n')
				maker.makepasslist()
			elif userinput.split()[1] == 'number':
				print('\nMode set to number list\n')
				maker.makenumlist()
			elif userinput.split()[1] == 'list':
				print(f'Available Modes: \n{availablemodes}')
			else:
				print('Mode not recognized. Type \'mode list\' to list all available modes')
		except IndexError:
			print('Format Incorrect - mode [mode to set]')
	elif userinput.lower() == 'help':
		print(f'{help}')			
	elif userinput.lower() == 'exit':
		print('Goodbye')
		break
	else:
		print('Command not recognized')
